#!/bin/bash

# This script was made thinking in the output generated by IDEA
# It is more easy for me, to run this bash rather than copy the 
# output jar to another path and executing, and blah, blah

function runtest(){
	filename=$1
	output_dir=test.output
	output_object=output.object
	command="java -jar ../out/artifacts/InterCoding_jar/InterCoding.jar -d $output_dir -o $output_object BaseTypes.java"
	echo =============================================================================
	echo RUNNING TEST FILE $filename
	$command $filename
	echo =============================================================================
	echo -n "TESTING SYNTAX RESULTING CODE ......................................   "
	dirpath=$(cat $filename | grep -oE "^package [^;]*" | sed "s#package ##g" | sed "s#\.#/#g")
	pycompile "$output_dir/$dirpath" 2> /tmp/aaaa1
	result=$(cat /tmp/aaaa1)
	rm /tmp/aaaa1
	#if [ -z "$result" ]; then echo "OK"; else echo "BAD :("; echo -e $result; fi;
	if [ -z "$result" ]; then echo "OK"; else echo "BAD :("; pycompile "$output_dir/$dirpath"; fi;
	echo =============================================================================
	echo; echo;
}
#runtest Test01.java
#runtest Test02.java
#runtest Test03.java
#runtest Test04.java
#runtest Test05.java
#runtest Test06.java
#runtest Test07.java
#runtest Test08.java
#runtest Test09.java
runtest Test10.java
#runtest Test11.java
#runtest Test12.java
#runtest Test13.java
#runtest Test14.java
#runtest Test15.java