#!/bin/bash

# This script was made thinking in the output generated by IDEA
# It is more easy for me, to run this bash rather than copy the 
# output jar to another path and executing, and blah, blah

function runtest(){
	filename=$1
	output_dir=test.output
	output_object=output.object
	command="java -jar ../out/artifacts/InterCoding_jar/InterCoding.jar -d $output_dir -o $output_object BaseTypes.java"
	echo =============================================================================
	echo Running Test $filename
	echo =============================================================================
	$command $filename
}
runtest Test01.java
runtest Test02.java
runtest Test03.java
runtest Test04.java
runtest Test05.java
runtest Test06.java
runtest Test07.java
runtest Test08.java
#runtest Test09.java
#runtest Test10.java
#runtest Test11.java
#runtest Test12.java
#runtest Test13.java
#runtest Test14.java
#runtest Test15.java